<<begin
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
begin

i = 1
numbers = [1]
total_sum = 0

while(true)
  sum = numbers[i-1] + numbers[i-2]
  break if (sum >= 4000_000)

  if sum % 2 == 0
    total_sum += sum
  end

  numbers.push(sum)
  i += 1
end

p total_sum
